Repository anovote/org, pull requests merged in 2021-01, with the labels that each got.

#7 Add label automation script
  git_labels.js
Labels: feature

#21 Use case diagram
  diagrams/Use case diagram/anovote use case diagram documentation.md
  diagrams/Use case diagram/anovote use case diagram.vpp
  diagrams/Use case diagram/anovote use case diagram.vpp.bak_000f
  diagrams/Use case diagram/anovote use case diagram.vpp.bak_001d
  diagrams/Use case diagram/anovote use case diagram.vpp.bak_002d
  diagrams/Use case diagram/anovote use case diagram.vpp.bak_003d
  diagrams/Use case diagram/anovote use case diagram.vpp.bak_004d
  diagrams/Use case diagram/anovote use case diagram.vpp.bak_005d
  diagrams/Use case diagram/anovote use case diagram.vpp.bak_006d
  diagrams/Use case diagram/anovote use case diagram.vpp.bak_007d
Labels: documentation

#19 Activity diagram
  uml/Anovote activity diagram.pdf
  uml/Anovote activity diagram.vpd
Labels: documentation

#37 Add final preliminary report (.pdf)
  documents/preliminary-report.pdf
Labels: writing
